### ISSUE TITLE
Reactions

### ISSUE THREAD

**Issue by lukaszombiekiller** [Discord-Bot-Maker-Mods/DBM-Mods#123]
how do I exactly use the "add reaction" function I have been trying to use this for a long time. (a precise set of instructions would be great)

**Comment by lukaszombiekiller** [comment]
it says "right click -> insert emoji" but I do not see a "insert emoji"

**Comment by MrG0ld** [comment]
Maybe you don't have the Beta version of DBM installed

**Comment by Almeeida** [comment]
![](http://etcroot.pw/qgLL28)
