### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Reptajl** [Discord-Bot-Maker-Mods/DBM-Mods#126]
When I try to use edit channel action this appears: Please update your edit_channel_MOD.js in your projects action folder!

**Comment by LasseNiermann** [comment]
Hey!
Thank you for your bug report! The issue has been resolved and a fix was published (#128).
You can download the file [here](https://raw.githubusercontent.com/Discord-Bot-Maker-Mods/DBM-Mods/beta/actions/edit_channel_MOD.js).

Have a nice day!

**Comment by Reptajl** [comment]
Thanks very much !!!

niedz., 24 lut 2019 o 14:41 Lasse Niermann <notifications@github.com>
napisał(a):
