### ISSUE TITLE
delivery fails checking in send embed message not saving

### ISSUE THREAD

**Issue by freelancerleno** [Discord-Bot-Maker-Mods/DBM-Mods#134]
Hi,
I would like to use the "If Message Delivery Fails" parameter in "Send Embed Message" to check if it has been received in DM to a member but this function does not seem to work.
When I select "skip next action" (or another), it does not save.
That function work on the simple "send message".
Thanks !

**Comment by ZockerNico** [comment]
This is already fixed in the newest mod version.

**Comment by LasseNiermann** [comment]
Yes. Please use the latest beta version. It has been fixed :)

**Comment by freelancerleno** [comment]
That strange, I have did it 10 minutes ago but no change, what is the version ?

**Comment by LasseNiermann** [comment]
👍🏻 Have fun
