### ISSUE TITLE
Edit Channel not working with Voice Channels

### ISSUE THREAD

**Issue by Almeeida** [Discord-Bot-Maker-Mods/DBM-Mods#138]
https://github.com/Discord-Bot-Maker-Mods/DBM-Mods/blob/ed2a04dd1e8e1113540e97068f27b26b46c5968e/actions/edit_channel_MOD.js#L147

This is the reason Edit Channel doesn't work with Voice Channels.

`this.getChannel` is for Text Channels. To get Voice Channels you must use `this.getVoiceChannel` (See bot.js line 713)

Maybe add a Field to choose if you want to edit a Text or a Voice Channel

**Comment by Korithex** [comment]
tried changing the this.getChannel to this.getVoiceChannel and it still logged "Please update edit-channel-MOD.js" on console. Needs to be fixed lol

**Comment by LasseNiermann** [comment]
I am fixing it right now  ^

**Comment by LasseNiermann** [comment]
Probably fixed 😄 
https://github.com/Discord-Bot-Maker-Mods/DBM-Mods/commit/fdbbb8cda9055e7b0a2ec3c52c97d957444a5610
