### ISSUE TITLE
Create Channel Mod not working properly

### ISSUE THREAD

**Issue by JasperWorld** [Discord-Bot-Maker-Mods/DBM-Mods#161]
When trying to set the channel in a category, this error appears: 
typeerror: channel.setparent is not a function

**Comment by LasseNiermann** [comment]
Hey. Are you using the DBM Beta? That’s required in order to use some modifications.

**Comment by JasperWorld** [comment]
I am not using beta, although it was working on a glitch.com host, and stoped working when I transfered it to an Ubuntu machine.

**Comment by zachdoug24** [comment]
Upgrade to beta.

**Comment by JasperWorld** [comment]
Ok.. I still don't understand why it stopped working.
thx tho
