### ISSUE TITLE
edit channel

### ISSUE THREAD

**Issue by xKowal** [Discord-Bot-Maker-Mods/DBM-Mods#171]
Hello, i have a error in console:

Error with Event "Edit Channel", Action #6:
TypeError: Cannot read property 'edit' of null

On localhost (pc) working, but on vps not working.

**Comment by LasseNiermann** [comment]
Hey. 

Did you create your bot using the stable DBM version, put it on your vps and upgraded to the beta later? That would explain your issue. 

Kind regards,
Lasse

**Comment by LasseNiermann** [comment]
//closed due to inactivity :)

**Comment by Blaeriz** [comment]
i got same ussue aswell i think, i remade the project and it worked
