### ISSUE TITLE
Issue with "set role permissions 

### ISSUE THREAD

**Issue by HarmoGlace** [Discord-Bot-Maker-Mods/DBM-Mods#184]
Hi, I have this issue with "set role permissions" with "all permissions"
![unknown-155](https://user-images.githubusercontent.com/23212967/58375315-3e3ff180-7f50-11e9-86f6-251919944442.png)

**Comment by HarmoGlace** [comment]
I see, but with glitch this doesn't work :/

**Comment by St3ph32** [comment]
If you really need this command you can try to use a command but only for one permission at a time but it will take you longer.
