### ISSUE TITLE
Create Voice Channel Category set with User limit bug.

### ISSUE THREAD

**Issue by HeavyWolfPL** [Discord-Bot-Maker-Mods/DBM-Mods#187]
When bot creates a voice channel, where Category ID and User limit are already set it will first create voice channel without category with desired user limit, then it will remove user limit and move the channel to category.

1. Create a voice channel
2. Set Category ID and User limit
3. Run the command
4. See what happens

**Comment by ozerotr** [comment]
I have same problem...

**Comment by TheMonDon** [comment]
Hello, this has been solved in the latest mods a while ago you have to use discord.js 11.5.1.
