### ISSUE TITLE
Issue with "Check if user reacted"

### ISSUE THREAD

**Issue by HarmoGlace** [Discord-Bot-Maker-Mods/DBM-Mods#190]
Hi, I have this issue with "Check if user reacted"
![image](https://user-images.githubusercontent.com/23212967/59367720-f5a07a80-8d3c-11e9-9c57-6d2090e506ce.png)
Here is the action : 
![image](https://user-images.githubusercontent.com/23212967/59367827-326c7180-8d3d-11e9-9c4c-8bcd0c4223a5.png)

**Comment by Almeeida** [comment]
Most likely means the Source Reaction variable is undefined

**Comment by HarmoGlace** [comment]
It is
![image](https://user-images.githubusercontent.com/23212967/59368284-2f25b580-8d3e-11e9-9fbc-e741351a001e.png)

**Comment by HarmoGlace** [comment]
And here is my "find reaction"
![image](https://user-images.githubusercontent.com/23212967/59368586-e3bfd700-8d3e-11e9-8c4f-f9061211eb2e.png)

**Comment by HarmoGlace** [comment]
Here is the raw data (it's an event) : https://pastebin.com/raw/kK9bM5a7
