### ISSUE TITLE
Set Bot Activity not showing "Playing"

### ISSUE THREAD

**Issue by master3395** [Discord-Bot-Maker-Mods/DBM-Mods#192]
When i chose "Playing" as an activity, it doesn't work.
Any of the other options work.
It doesn't work in a clean bot, not even after i validate the files in steam either.
It shows "Property status "unknown"
![image](https://user-images.githubusercontent.com/4199669/59553007-490a0700-8f8f-11e9-87d4-95d3cb1cf6a0.png)

**Comment by 0DJ** [comment]
Nice Bro

**Comment by TheMonDon** [comment]
@master3395 Have you resolved this issue yet?

**Comment by master3395** [comment]
Nope, has always been an issue, around the time i reported this.
It is like this on a clean install on steam and in a clean bot folder.

**Comment by master3395** [comment]
Almeida just helped me figure out the issue.
The "Set Bot Activity"'s "Play" line, doesn't work.
But using "Set Bot Game"'s "Play" does.
There's too many mods for the same thing hm..
![image](https://user-images.githubusercontent.com/4199669/63213800-e3fa9b00-c110-11e9-8892-9136cc633db7.png)
