### ISSUE TITLE
Store Channel Info: Channel Category Name :: Stops whole action sequence if null.

### ISSUE THREAD

**Issue by TheMonDon** [Discord-Bot-Maker-Mods/DBM-Mods#194]
If a channel category is null the store channel info: channel category name will stop and break the rest of the action sequence.

**Comment by Almeeida** [comment]
https://github.com/Discord-Bot-Maker-Mods/DBM-Mods/blob/86a1267f08e79d23dd2cb144a9f576257effc940/actions/store_channel_info.js#L231
Change the line above to: 
```javascript
result = targetChannel.parent && targetChannel.parent.name; 
```
