### ISSUE TITLE
REQUEST: doesn't exist "join voice channel"

### ISSUE THREAD

**Issue by Cathuntrs13** [Discord-Bot-Maker-Mods/DBM-Mods#217]
Hello so um... In my discord bot maker doesn't exist the action "Join voice channel"

**Comment by TheMonDon** [comment]
This isn't a mod, you need to have DBM Beta.

**Comment by Cathuntrs13** [comment]
How can I get the DBM Beta?

**Comment by dcorvus** [comment]
Don't make idiotic bug reports.
