### ISSUE TITLE
Member deafened is removed in the latest version of Store Member Info

### ISSUE THREAD

**Issue by master3395** [Discord-Bot-Maker-Mods/DBM-Mods#219]
Member deafened is removed in the latest version of Store Member Info

![old_action_store_member_info](https://user-images.githubusercontent.com/4199669/63111651-6e66c180-bf8e-11e9-81e1-af25906d1ef0.JPG)

![unknown](https://user-images.githubusercontent.com/4199669/63111657-732b7580-bf8e-11e9-85d5-02affaaf3ed4.png)

**Comment by TheMonDon** [comment]
Shit. I'll look into it

**Comment by TheMonDon** [comment]
This is intentional, it was moved to use check if member mod as it was already in there.

**Comment by master3395** [comment]
Ok, just wish it had 
Store in:
Temp Variable
option.
![image](https://user-images.githubusercontent.com/4199669/63112869-99064980-bf91-11e9-9c6c-f265e730ab55.png)
