### ISSUE TITLE
File Control not Writing To File.

### ISSUE THREAD

**Issue by jamiethegreatQ777** [Discord-Bot-Maker-Mods/DBM-Mods#224]
Using the file control action creates the file, however places no text inside at all.
![image](https://user-images.githubusercontent.com/50340593/64915687-ceef4700-d764-11e9-9b7a-e1543d09f686.png)

![image](https://user-images.githubusercontent.com/50340593/64915696-f219f680-d764-11e9-929a-e81d1607f694.png)

**Comment by DetroitWhiskey136** [comment]
Update to the latest version
