### ISSUE TITLE
Join audio channel is missing

### ISSUE THREAD

**Issue by Searchcat37** [Discord-Bot-Maker-Mods/DBM-Mods#232]
The join channel command under audio control is missing and in the logs it says:
DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'simple-youtube-api'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'simple-youtube-api' does not exist!
Command failed: npm install simple-youtube-api --loglevel=error --save
Error with Event "Play YouTube Playlist", Action #1: Error: Cannot find module 'simple-youtube-api

**Comment by dcorvus** [comment]
Legitimately tells you what to do. Don't run it in DBM.

**Comment by Searchcat37** [comment]
?

**Comment by dada513** [comment]
Run your bot in command line. Make sure you have nodejs installed.

1. Open your terminal ( in Windows - type cmd in the app search bar )
2. Type cd C:/YourProjectDirectory
3. Run node bot.js

**Comment by Searchcat37** [comment]
Thank You
