### ISSUE TITLE
Need help, please read.

### ISSUE THREAD

**Issue by andretunes** [Discord-Bot-Maker-Mods/DBM-Mods#233]
Hello, since the only method to contact you is thought here, i've been banned from your discord server for telling that i used cracked version. I'm feel bad and i tell sorry for that, so i buyed the Discord Bot Maker in Steam, i can send prints whatever, I just wanna stay in you Discord Server.
Kind Regards!

**Comment by Almeeida** [comment]
appeal yours warnings at https://dbm-support.site

**Comment by andretunes** [comment]
Thank you!
