### ISSUE TITLE
Game_server.js

### ISSUE THREAD

**Issue by daneleo** [Discord-Bot-Maker-Mods/DBM-Mods#239]
could we possibly update it to use gamedig query instead of the game-server-query as its not used anymore and apparently got DMCAed, Gamedig also has more games added
https://www.npmjs.com/package/gamedig

**Comment by dcorvus** [comment]
There is no reason to make an Issue for this. You are more than capable of making a mod-suggestion or similar for this. The game-server-query is still used, still working just fine. Don't make issues for things like this again.

**Comment by DetroitWhiskey136** [comment]
second it already uses gamedig in the latest version
update your shit before complaining
