### ISSUE TITLE
Loop through List - Server Members

### ISSUE THREAD

**Issue by D0ggy2702** [Discord-Bot-Maker-Mods/DBM-Mods#263]
Seems to be broken, does return nothing, but got 6 Members on my Discord Server.

**Comment by KendyCZ01** [comment]
Could you please screenshot the event & action?

**Comment by D0ggy2702** [comment]
https://i.gyazo.com/f8cde918bde6d3c41d07d760d78ce5c5.png - everthing beyond the loop command, does not execute

**Comment by Almeeida** [comment]
That's not how the loop works.
