### ISSUE TITLE
Install Bug

### ISSUE THREAD

**Issue by SoloMaker** [Discord-Bot-Maker-Mods/DBM-Mods#39]
I installed the mod like I was instructed to. The new actions show up in Discord Bot Maker, but when I try to use the commands that I made with actions from the mod, those actions just get skipped.

**Comment by LasseNiermann** [comment]
Would you please check your bot log?

**Comment by SoloMaker** [comment]
![botlog](https://user-images.githubusercontent.com/41548977/43048634-0af50628-8deb-11e8-89ec-4438614b300d.PNG)

**Comment by LasseNiermann** [comment]
Mhh.. I can suggest you to run your bot with command line to see hidden errors. More information are available on the DBM Mods Discord here https://dbm-network.com

**Comment by SoloMaker** [comment]
Danke.
