### ISSUE TITLE
youtube-search and dependancies

### ISSUE THREAD

**Issue by Nickster1212** [Discord-Bot-Maker-Mods/DBM-Mods#45]
i tried manually installing "youtube-search" because it wouldnt do it on its own. But for some reason when i run the command in the prompt, it gives me this-

C:\Users\User\InfoBot>npm install youtube-search
npm WARN discord.js@11.4.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.4.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN Discord-Bot-Maker-Bot@1.2.9 No description
npm WARN Discord-Bot-Maker-Bot@1.2.9 No repository field.
npm WARN Discord-Bot-Maker-Bot@1.2.9 No license field.

+ youtube-search@1.1.1
updated 1 package and audited 264 packages in 1.472s
found 0 vulnerabilities

what are the peer dependancies that i need to install myself? what am i doing wrong?

**Comment by Nickster1212** [comment]
what do you mean? it wont let me use the command still

**Comment by lucasboss45** [comment]
I just answered you don't worry about those.

**Comment by Nickster1212** [comment]
to make my question more clear...

DBM MODS (Node Module Installer v2.1) Attempting To Install Node Module: 'youtube-search'. Please wait...
DBM MODS (Node Module Installer v2.1): Node Module 'youtube-search' does not exist!
Command failed: npm install youtube-search --loglevel=error --save
Error: Bad Request

its giving me this in the testing log

**Comment by lucasboss45** [comment]
Well I already told you to move to the support channels so I want help anymore here...

**Comment by Nickster1212** [comment]
okay... wheres the support channel

**Comment by Danno3817** [comment]
This is the link to the Mods support guild https://discord.gg/z5bmGf9
